import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        inter.variable,
        // ~lg: header without tabs (14) + TOCCollapsed (10) + padding (4)
        // lg~xl: header (14) + nav links (10) + TOCCollapsed (10) + padding (4)
        // xl~: header (14) + nav links (10)  + padding (4)
        'scroll-pt-28 lg:scroll-pt-38 xl:scroll-pt-28',
      )}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute={'class'} defaultTheme={'system'} enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
